select ?lemma WHERE {
  ?lexemeId dct:language wd:Q9176; # Korean
            wikibase:lexicalCategory wd:Q1084; # Noun
            wikibase:lemma ?lemma.

  FILTER (
    REGEX(str(?lemma), '^[가-힣]+$')
    && strlen(str(?lemma)) < 4
  )
}
ORDER BY ?lemma
